# Generated by Django 4.0.3 on 2022-03-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0003_alter_team_electricity_alter_team_exploration_days_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
        migrations.RemoveField(
            model_name='team',
            name='exploration_days',
        ),
        migrations.RemoveField(
            model_name='team',
            name='explorers',
        ),
        migrations.AddField(
            model_name='team',
            name='explorers1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='explorers2',
            field=models.IntegerField(default=0),
        ),
    ]
