# Generated by Django 4.0.3 on 2022-03-30 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0004_delete_new_remove_team_exploration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='steel',
            field=models.IntegerField(default=40),
        ),
    ]
