# Generated by Django 4.0.3 on 2022-03-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0005_alter_team_steel'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='oxygen',
            field=models.CharField(default='69%', max_length=10),
        ),
    ]
