# Generated by Django 4.0.3 on 2022-03-31 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0006_team_oxygen'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='sideQres',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='sidequest',
            field=models.IntegerField(default=0),
        ),
    ]
